address=/randnet.ne.jp/127.0.0.1
address=/login.randnet.ne.jp/127.0.0.1
address=/www.randnet.ne.jp/127.0.0.1
address=/member.randnet.ne.jp/127.0.0.1
address=/mail.randnet.ne.jp/127.0.0.1
address=/news.randnet.ne.jp/127.0.0.1
address=/service.randnet.ne.jp/127.0.0.1
